services:
  # A Docker web service
  - type: web
    name: MW_RENAME
    env: python
    startCommand: python3 bot.py
    buildCommand: pip3 install -U -r requirements.txt
    repo: https://github.com/Movies-world/MW-RENAME.git # optional
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: main # optional (defaults to master)
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: FORCE_SUB 
        sync: false
      - key: DB_NAME 
        sync: false
      - key: DB_URL 
        sync: false 
      - key: START_PIC 
        sync: false
      - key: ADMIN 
        sync: false    
    autoDeploy: true 
